### ISSUE TITLE
Dev Centre House - SEO Checklist

### ISSUE THREAD

**Issue by Twanawebtech** [DevCenterHouse/cmpd.ie#4]
- [x] Setup [Google Tag Manager](https://marketingplatform.google.com/about/tag-manager/).
- [x] Setup [Google Analytics](https://marketingplatform.google.com/about/analytics/).
- [x] Setup [Google Search Console](https://www.google.com/webmasters/tools/home).
- [x] Create an XML sitemap and submit it to [Google Search Console](https://www.google.com/webmasters/tools/home).
- [x] Create a robots.txt and submit it to [Google Search Console](https://www.google.com/webmasters/tools/home).
- [x] Perform keyword research using [Google AdWords Keyword Planner](https://adwords.google.com/intl/ru/home/tools/keyword-planner/).
- [x] Include some keywords in the title tag.
- [x] Include some keywords in meta description tag.
- [x] Include the primary keyword in a H1 tag (only one H1 tag per page is recommended).
- [x] Use the keywords 3 times across each page.
- [x] Use LSI for the primary keyword using [LSIGraph](https://lsigraph.com).
- [x] Use synonyms of the keywords if already used 3 times directly on the page.
- [x] Descriptive file names and alt tags for images.
- [x] Use good descriptive anchor text for internal links. Avoid using links such as "learn more".
- [x] Check for crawl errors, duplicate content errors, missing titles and more using Google Search Console.
- [x] Identify bad redirects (302's that should be 301's) with the aid of [Browseo](http://www.browseo.net).
- [x] Avoid duplicate content on pages.
- [x] Check [Google PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/).
